routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "Site\HomeController@index");
//Route::get('/vantagens', "Site\HomeController@vantagens");
Route::get('/vantagens', "Site\HomeController@quemSomos");
Route::get('/conheca-o-plano', "Site\HomeController@conhecaPlano");
Route::post('/fale-conosco', "Site\HomeController@faleConosco")->name('faleconosco');

Route::get('/cases-de-sucesso', "Site\HomeController@casesDeSucesso");
Route::get('/seja-nosso-socio', "Site\SejaNossoSocioController@index");
Route::post('/seja-nosso-socio/salvar', "Site\SejaNossoSocioController@store")->name('seja-nosso-socio');
Route::get('/quero-entrar-no-marketing-em-rede/{id}', "Site\SejaNossoSocioController@ativarSocio");

Route::get("/cidades","Site\HomeController@cidades" );

Auth::routes();

Route::namespace('Painel')->group(function () {
	Route::prefix('painel')->group(function () {
		Route::get('home', 'HomeController@index')->name('home');
		Route::resource('cases', 'CaseController');
		Route::resource('cases/{caseID}/imagens', 'CaseImagemController');
		Route::resource('planos', 'PlanoController');
		Route::resource('vantagens', 'VantagemController');
		Route::resource('produtos', 'ProdutoController');
		Route::resource('socios', 'SocioController');
		Route::resource('socios/{socioID}/usuario', 'UsuarioController');

		Route::resource('solicitacoes', 'SolicitacaoController');

	});
});

Route::namespace('VirtualOffice')->group(function () {
	Route::prefix('virtual-office')->group(function () {
		Route::get('login','LoginController@index');
		Route::post('login','LoginController@login');
	});
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') - {{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

    <!-- Styles -->
    <link href="{{ asset('css/dropzone.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/painel.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                        @if(Auth::user()->is_patrocinador == 1)
                        <li class="nav-item @if(Request::is('painel/cases*')) active @endif">
                            <a class="nav-link" href="{{ route('cases.index') }}"><i class="fas fa-suitcase"></i> Cases de Sucesso</a>
                        </li>
                        <li class="nav-item @if(Request::is('painel/planos*')) active @endif">
                            <a class="nav-link" href="{{ route('planos.index') }}"><i class="fas fa-file-invoice-dollar"></i> Planos</a>
                        </li>
                        <li class="nav-item @if(Request::is('painel/vantage*')) active @endif">
                            <a class="nav-link" href="{{ route('vantagens.index') }}"><i class="fas fa-tasks"></i> Vantagens</a>
                        </li>
                        <li class="nav-item @if(Request::is('painel/produtos*')) active @endif">
                            <a class="nav-link" href="{{ route('produtos.index') }}"><i class="fab fa-product-hunt"></i> Produtos</a>
                        </li>
                        <li class="nav-item @if(Request::is('painel/socios*')) active @endif">
                            <a class="nav-link" href="{{ route('socios.index') }}"><i class="fas fa-user-tie"></i> Sócios</a>
                        </li>
                        <li class="nav-item @if(Request::is('painel/solicitacoes*')) active @endif">
                            <a class="nav-link" href="{{ route('solicitacoes.index') }}"><i class="fab fa-slideshare"></i> Solicitaões de Apresentação</a>
                        </li>
                        @else
                        <li class="nav-item @if(Request::is('painel/produtos*')) active @endif">
                            <a class="nav-link" href="{{ route('produtos.index') }}"><i class="fab fa-product-hunt"></i> Produtos</a>
                        </li>
                        <li class="nav-item @if(Request::is('painel/solicitacoes*')) active @endif">
                            <a class="nav-link" href="{{ route('solicitacoes.create') }}"><i class="fab fa-slideshare"></i> Solicitar Apresentação</a>
                        </li>
                        @endif
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>

                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                                     <i class="fas fa-sign-out-alt"></i> {{ __('Sair') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="{{ asset('js/jquery.mask.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    @yield('script')
    <script src="{{ asset('js/painel.js') }}"></script>
</body>
</html>

resources/views/layouts/footer.blade.php
<section class="footer">
      <div class="container">
      <div class="row">
        <div class="col-6">
          <h2 class="title">Quero mais informações</h2>
          <p>
          <img width="24" height="24" src="{{ asset('img/whatsapp-brands.svg')}}"/>
          (93) 99191-3691
          </p>
          <div class="row">
          <form class="col-8" id="formContato" method="post" action="{{ route('faleconosco')}}">
            @csrf
            <div class="form-group">
              <input type="text" placeholder="Nome" name="nome" class="form-control form-control-lg ">
            </div>
            <div class="form-group">
              <input type="email" placeholder="E-mail" name="email" class="form-control form-control-lg">
            </div>
            <div class="form-group">
              <textarea name="mensagem" placeholder="Mensagem" class="form-control form-control-lg"></textarea>
            </div>
            <button type="submit">
              <img src="{{ asset('img/btn-enviar.png')}}">
            </button>
          </form>
          </div>
        </div>
        <div class="col-6 text-right pt-8 text-white">
          <p class="text-warning">SIGA-NOS
          <a href="https://www.facebook.com/sousucessobr/?modal=admin_todo_tour" target="_blank">
            <img src="{{ asset('img/facebook.png')}}">
          </a>
          <img src="{{ asset('img/instagram.png')}}">
          </p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p>Consultor independente associada ao grupo <img src="{{ asset('img/hinode.png')}}"></p>
          <p>Venha fazer parte do grupo Sou Sucesso<br> e crescer com a gente no Marketing de Rede.</p>
          <p>
            <a href="http://www.w3mais.com" target="_blank">
                <img src="{{ asset('img/w3mais.png')}}">
            </a>
          </p>

        </div>
      </div>
      </div>
     </section>

resources/views/layouts/menu.blade.php
<div class="container">


        <a class="navbar-brand" href="{{ url('/')}}" title="Sou Sucesso">
          <img src="{{ asset('img/logomarca.png') }}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse float-right text-right" id="navbarSupportedContent">
          <ul class="navbar-nav float-right text-right">
            <li class="nav-item @if(Request::is('conheca-o-plano')) active @endif">
              <a class="nav-link" href="{{ url('conheca-o-plano') }}">Conheça o plano</a>
            </li>
            <li class="nav-item @if(Request::is('vantagens')) active @endif">
              <a class="nav-link" href="{{ url('vantagens')}}">Vantagens</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.hinodeonline.com.br/?id_consultor=22886156" target="_blank">Produtos</a>
            </li>

            <li class="nav-item @if(Request::is('cases-de-sucesso')) active @endif">
              <a class="nav-link" href="{{ url('cases-de-sucesso')}}">Cases de sucesso</a>
            </li>
            <li class="nav-item  @if(Request::is('seja-nosso-socio')) active @endif">
              <a class="nav-link" href="{{ url('seja-nosso-socio') }}">Seja nosso sócio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-warning" href="{{ url('virtual-office/login')}}">Virtual office</a>
            </li>
          </ul>

        </div>
        </div>

resources/views/layouts/nav-black.blade.php
<nav class="navbar navbar-expand-lg fixed-top navbar-fixed">
  @include('layouts.menu')        
</nav>

resources/views/layouts/nav.blade.php
<nav class="navbar1 navbar navbar-expand-lg fixed-top">
  @include('layouts.menu')         
</nav>

resources/views/layouts/site.blade.php
<!doctype html>
<html lang="pt_br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="{{ asset('css/select2-bootstrap.css') }}">
    <link rel="stylesheet" href="{{ asset('css/estilo.css') }}">

    <title>Sou Sucesso</title>
  </head>
  <body>
    <div class="site">
        @yield('content')
        @include("layouts.footer") 
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="http://malsup.github.io/jquery.cycle2.js"></script>
    <script src="http://malsup.github.io/jquery.cycle2.carousel.js"></script>
    <script src="{{ asset('js/jquery.mask.min.js')}}"></script>
    <script src="{{ asset('js/sousucesso.js')}}"></script>
    
  </body>
</html>