routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "Site\HomeController@index");
//Route::get('/vantagens', "Site\HomeController@vantagens");
Route::get('/vantagens', "Site\HomeController@quemSomos");
Route::get('/conheca-o-plano', "Site\HomeController@conhecaPlano");
Route::post('/fale-conosco', "Site\HomeController@faleConosco")->name('faleconosco');

Route::get('/cases-de-sucesso', "Site\HomeController@casesDeSucesso");
Route::get('/seja-nosso-socio', "Site\SejaNossoSocioController@index");
Route::post('/seja-nosso-socio/salvar', "Site\SejaNossoSocioController@store")->name('seja-nosso-socio');
Route::get('/quero-entrar-no-marketing-em-rede/{id}', "Site\SejaNossoSocioController@ativarSocio");

Route::get("/cidades","Site\HomeController@cidades" );

Auth::routes();

Route::namespace('Painel')->group(function () {
	Route::prefix('painel')->group(function () {
		Route::get('home', 'HomeController@index')->name('home');
		Route::resource('cases', 'CaseController');
		Route::resource('cases/{caseID}/imagens', 'CaseImagemController');
		Route::resource('planos', 'PlanoController');
		Route::resource('vantagens', 'VantagemController');
		Route::resource('produtos', 'ProdutoController');
		Route::resource('socios', 'SocioController');
		Route::resource('socios/{socioID}/usuario', 'UsuarioController');

		Route::resource('solicitacoes', 'SolicitacaoController');

	});
});

Route::namespace('VirtualOffice')->group(function () {
	Route::prefix('virtual-office')->group(function () {
		Route::get('login','LoginController@index');
		Route::post('login','LoginController@login');
	});
});

app/Http/Controllers/Painel/CaseController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\CaseSucesso;
use App\Http\Requests\CasesRequest;

class CaseController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

        $this->middleware('patrocinador');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cases = CaseSucesso::orderBy('id','DESC')->paginate(20);
        return view('painel.cases.index',compact('cases'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('painel.cases.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CasesRequest $request)
    {
        CaseSucesso::create($request->all());
        return redirect()->route('cases.index')->with('message','Cadastro realizado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $case = CaseSucesso::findOrFail($id);
        return view('painel.cases.edit',compact('case'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CasesRequest $request, $id)
    {
        $case = CaseSucesso::findOrFail($id);
        $case->update($request->all());

        return redirect()->route('cases.index')->with('message','Cadastro editado com sucesso!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        CaseSucesso::findOrFail($id)->delete();
        
        return redirect()->route('cases.index')->with('message','Cadastro apagado com sucesso!');
    }
}

app/Http/Controllers/Painel/CaseImagemController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\CaseSucesso;
use App\Models\CaseImagem;

class CaseImagemController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

        $this->middleware('patrocinador');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($idCase)
    {
        $case = CaseSucesso::findOrfail($idCase);
        $imagens = $case->imagens;
        return view('painel.cases.imagens.index',compact('case','imagens'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($idCase)
    {
        $case = CaseSucesso::findOrfail($idCase);
        return view('painel.cases.imagens.create',compact('case'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$id)
    {
        @symlink (storage_path("app"), public_path('app'));
        if ($request->hasFile('file')) {
            if ($request->file('file')->isValid()) {

                $nameFile = date("Ymd")."_".str_slug($request->file->getClientOriginalName());
                $extension = $request->file->extension();
                $path = $request->file->storeAs('cases', $nameFile.".".$extension);

                CaseImagem::create([
                    'case_id' => $id,
                    'imagem' => $path
                ]);
            }
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Painel/PlanoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Plano;
use App\Http\Requests\PlanosRequest;

class PlanoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

        $this->middleware('patrocinador');

    }
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $planos = Plano::orderBy('id','DESC')->paginate(10);
        return view('painel.planos.index',compact('planos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('painel.planos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PlanosRequest $request)
    {
        $plano = $request->all();
        $plano['valor'] = str_replace("R$ ","",$plano['valor']);
        $plano['valor'] = str_replace(".","",$plano['valor']);
        $plano['valor'] = str_replace(",",".",$plano['valor']);
        Plano::create($plano);
        return redirect()->route('planos.index')->with('message','Cadastro realizado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $case = Plano::findOrFail($id);
        return view('painel.planos.edit',compact('case'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PlanosRequest $request, $id)
    {
        $case = Plano::findOrFail($id);
        $plano = $request->all();
        $plano['valor'] = str_replace("R$ ","",$plano['valor']);
        $plano['valor'] = str_replace(".","",$plano['valor']);
        $plano['valor'] = str_replace(",",".",$plano['valor']);
        $case->update($plano);

        return redirect()->route('planos.index')->with('message','Cadastro editado com sucesso!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Plano::findOrFail($id)->delete();
        
        return redirect()->route('planos.index')->with('message','Cadastro apagado com sucesso!');
    }
}

app/Http/Controllers/Painel/ProdutoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Produto;
use App\Http\Requests\ProdutosRequest;

class ProdutoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

        $this->middleware('socio')->only('index','show');

        $this->middleware('patrocinador')->only('create','store','edit','update','destroy');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produtos = Produto::orderBy('id','DESC')->paginate(10);
        return view('painel.produtos.index',compact('produtos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('painel.produtos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProdutosRequest $request)
    {
        Produto::create($request->all());
        return redirect()->route('produtos.index')->with('message','Cadastro realizado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $produto = Produto::findOrFail($id);
        return view('painel.produtos.show',compact('produto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $case = Produto::findOrFail($id);
        return view('painel.produtos.edit',compact('case'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProdutosRequest $request, $id)
    {
        $case = Produto::findOrFail($id);
        $case->update($request->all());

        return redirect()->route('produtos.index')->with('message','Cadastro editado com sucesso!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Produto::findOrFail($id)->delete();
        
        return redirect()->route('produtos.index')->with('message','Cadastro apagado com sucesso!');
    }
}

app/Http/Controllers/Painel/SocioController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Socio;
use App\User;

class SocioController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

        $this->middleware('patrocinador');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $socios = Socio::orderBy('id','DESC')->paginate(50);
        return view('painel.socios.index',compact('socios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $socio = Socio::findOrFail($id);
        return view('painel.socios.show',compact('socio'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $socio = Socio::findOrFail($id);
        User::where('id',$socio->user_id)->delete();
        $socio->delete();

        return redirect()->route('socios.index')->with('message','Sócio <b>'.$socio->nome.'</b> excluído com sucesso!!');
    }
}

app/Http/Controllers/Painel/SolicitacaoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Solicitacao;
use App\Mail\SolicitacaoMail;
use App\Http\Requests\SolicitacaoRequest;
use Carbon\Carbon;

class SolicitacaoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $solicitacoes = Solicitacao::orderBy('id','DESC')->paginate(50);

        return view('painel.solicitacoes.index',compact('solicitacoes'));
    }

    public function create(){
    	return view('painel.solicitacoes.create');
    }

    public function store(SolicitacaoRequest $request)
    {
        
        $dados = $request->all();
        $d = explode("/",$dados['data']);
        $dados['data'] = $d[2]."-".$d[1]."-".$d[0];
        $solicitacao = Solicitacao::create($dados);


        \Mail::to('williamsbsi@gmail.com')->send(new SolicitacaoMail($solicitacao));

        return redirect()->route('solicitacoes.create')->with('message','Sua solicitação foi enviada com sucesso! Aguarde o nosso retorno, obrigado!');


    }
}

resources/views/painel/vantagens/create.blade.php
@extends('layouts.app')

@section('title', (isset($titlePage)? $titlePage : 'Vantagens'))

@section('content')
<div class="container">
<div class="card card-primary">
  <div class="card-header">
    <div class="row">
      <div class="col-6">
        <h2>Cadastrar</h2>
      </div>
      <div class="col-6">
        <ul class="nav justify-content-end">
          <li class="nav-item">
            <a href="{{ route('vantagens.index') }}" class="nav-link btn btn-primary">Listar Vantagens</a>
          </li>
        </ul>
      </div>
    </div>
    
    
  </div>

  <!-- /.box-header -->
  <!-- form start -->
  {{ Form::open(['role' => 'form', 'method' => 'POST', 'route' => 'vantagens.store', 'files' => true])}}
    @include('painel.vantagens.form')
   	<div class="card-footer">
      <button type="submit" class="btn btn-primary">Cadastrar</button>
    </div>
  {{ Form::close() }}
</div>
</div>
@endsection

resources/views/painel/vantagens/edit.blade.php
@extends('layouts.app')

@section('title', (isset($titlePage)? $titlePage : 'Vantagens'))

@section('content')
<div class="container">
<div class="card box-primary">
  <div class="card-header with-border">
    <h3 class="box-title">Editar Vantagens</h3>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  {{ Form::model($vantagem,['role' => 'form', 'method' => 'PUT', 'route' => ['vantagens.update',$vantagem->id],'files' => true])}}
    
    @include('painel.vantagens.form')

    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Editar</button>
    </div>
  {{ Form::close() }}
</div>
</div>
@endsection

resources/views/painel/vantagens/form.blade.php
<div class="card-body">
  
  <div class="form-group{{ $errors->has('titulo') ? ' has-error' : '' }}">
    {{ Form::label('Título *') }}
    {{ Form::text('titulo',null, ['class' => 'form-control']) }}
    @if ($errors->has('titulo'))
    <span class="help-block">
      {{ $errors->first('titulo') }}
    </span>
    @endif
  </div>
  <div class="form-group{{ $errors->has('url') ? ' has-error' : '' }}">
    {{ Form::label('URL') }}
    {{ Form::url('url',null, ['class' => 'form-control']) }}
    @if ($errors->has('url'))
    <span class="help-block">
      {{ $errors->first('url') }}
    </span>
    @endif
  </div>
  <div class="form-group{{ $errors->has('imagem') ? ' has-error' : '' }}">
    {{ Form::label('Imagem *') }}
    {{ Form::file('imagem', ['class' => 'form-control-file']) }}
    @if ($errors->has('imagem'))
    <span class="help-block">
      {{ $errors->first('imagem') }}
    </span>
    @endif
  </div>
  <div class="form-group{{ $errors->has('descricao') ? ' has-error' : '' }}">
    {{ Form::label('Descrição *') }}
    {{ Form::textarea('descricao',null, ['class' => 'form-control ckeditor']) }}
    @if ($errors->has('descricao'))
    <span class="help-block">
      {{ $errors->first('descricao') }}
    </span>
    @endif
  </div>
</div>
@section('script')
  @parent
  <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
@endsection

resources/views/painel/vantagens/index.blade.php
@extends('layouts.app')

@section('title', (isset($titlePage)? $titlePage : 'Vantagens'))


@section('content')
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="card">
				<div class="card-header">
            <div class="row">
             <div class="col-6">
              <h2 class="">Vantagens</h2>
             </div>
             <div class="col-6">
              <ul class="nav justify-content-end">
                <li class="nav-item">
                  <a href="{{ route('vantagens.create')}}" class="nav-link btn btn-primary">Cadastrar</a>
                </li>
              </ul>
             </div>
            </div>  
             
            </div>
			
      		<div class="card-body table-responsive">
              @if (session('message'))
                  <div class="alert alert-success">
                      {{ session('message') }}
                  </div>
              @endif
              <table class="table table-bordered table-hover">
                <tr>
                  <th>
                    <input type="checkbox" name="selecionarTodos" title="Selecionar Todos" class="select-input-all">
                  </th>
                  					
                  <th>Nome</th>                 
						      <th>Imagem</th>
						      <th colspan="2" class="text-center" width="10%">Ações</th>
                </tr>
                @foreach($vantagens as $vantagem)
                <tr>
                  <td width="3%">                    
                    <input class="arrayid" type="checkbox" name="id" value="{{ $vantagem->id }}">
                  </td>	
                 
						      <td>{{ $vantagem->titulo }}</td>
						      <td>
                    <img src="{{ asset($vantagem->imagem) }}"/>
                  </td>
                  <td class="text-center">
                    
                    <a class="btn btn-warning" href="{{ route('vantagens.edit', $vantagem->id )}}" title="Editar"><i class="far fa-edit"></i></a>
                    
                  </td>
                  <td class="text-center"> 
                    {!! Form::open(['route' => ['vantagens.destroy',$vantagem->id], 'method' => 'DELETE']) !!}
                      <button class="btn btn-danger" type="submit" title="Remover"><i class="fa fa-trash" aria-hidden="true"></i></a>
                    {!! Form::close() !!}
                    
                  </td>
                </tr>
                @endforeach
              </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              {{ $vantagens->render() }}
            </div>
          </div>
          <!-- /.box -->
		</div>	
	</div>
</div>
@stop